version: '3.8'
services:
  chat-service:
    build: .
    container_name: chat-microservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - rm_traceability_network

networks:
  rm_traceability_network:
    external: true
